<a href="https://colab.research.google.com/github/kyook17/BADM576/blob/main/BADM576_Assignment2_Insurance_Data_Analysis_Kiwook_Song.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

# Load the Excel file
df = pd.read_csv("https://raw.githubusercontent.com/kyook17/BADM576/main/csv/insurance_marketing_dataset.csv")
print(df.shape, "\n")
df.head()

(9134, 24)

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,BU79786,Washington,2763.519279,No,Basic,Bachelor,2/24/11,Employed,F,56274,...,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,QZ44356,Arizona,6979.535903,No,Extended,Bachelor,1/31/11,Unemployed,F,0,...,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,AI49188,Nevada,12887.431650,No,Premium,Bachelor,2/19/11,Employed,F,48767,...,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,WW63253,California,7645.861827,No,Basic,Bachelor,1/20/11,Unemployed,M,0,...,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,HB64268,Washington,2813.692575,No,Basic,Bachelor,2/3/11,Employed,M,43836,...,44,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize

In [3]:
# Select the columns for analysis
columns_for_analysis = [
    'Response',                 # Nominal, Engagement Metrics
    'Education',                # Ordinal, Customer Demographics
    'Income',                   # Continuous, Customer Demographics
    'Number of Policies',       # Discrete, Policy Information
    'Total Claim Amount',       # Continuous, Financial Information
]

In [7]:
# Extract the selected columns for descriptive analysis
selected_columns_data = df[columns_for_analysis]

# Perform descriptive analysis for each selected column

# For the nominal column 'Response'
customer_response = selected_columns_data['Response'].value_counts()
print("Response Stats:\n", customer_response)

Response Stats:
 No     7826
Yes    1308
Name: Response, dtype: int64

In [10]:
# For the ordinal column 'Education'
education_order = ['High School or Below', 'Bachelor', 'College', 'Master', 'Doctor']
education_counts = selected_columns_data['Education'].astype('category')
education_counts = education_counts.cat.set_categories(education_order, ordered=True)
education_counts = education_counts.value_counts().sort_index()
print("Education Stats:\n", education_counts)

Education Stats:
 High School or Below    2622
Bachelor                2748
College                 2681
Master                   741
Doctor                   342
Name: Education, dtype: int64

In [11]:
# For the continuous column 'Income'
income_stats = selected_columns_data['Income'].describe()
print("Income Stats:\n", income_stats)

Income Stats:
 count     9134.000000
mean     37657.380009
std      30379.904734
min          0.000000
25%          0.000000
50%      33889.500000
75%      62320.000000
max      99981.000000
Name: Income, dtype: float64

In [12]:
# For the discrete column 'Number of Policies'
num_of_policies_stats = selected_columns_data['Number of Policies'].describe()
num_of_policies_freq = selected_columns_data['Number of Policies'].value_counts()
print("Number of Policies Stats:\n", num_of_policies_stats)
print("Number of Policies Frequencies:\n", num_of_policies_freq)

Number of Policies Stats:
 count    9134.000000
mean        2.966170
std         2.390182
min         1.000000
25%         1.000000
50%         2.000000
75%         4.000000
max         9.000000
Name: Number of Policies, dtype: float64
Number of Policies Frequencies:
 1    3251
2    2294
3    1168
7     433
9     416
4     409
5     407
8     384
6     372
Name: Number of Policies, dtype: int64

In [13]:
# For the continuous column 'Total Claim Amount'
total_claim_amount_stats = selected_columns_data['Total Claim Amount'].describe()
print("Total Claim Amount Stats:\n", total_claim_amount_stats)

Total Claim Amount Stats:
 count    9134.000000
mean      434.088794
std       290.500092
min         0.099007
25%       272.258244
50%       383.945434
75%       547.514839
max      2893.239678
Name: Total Claim Amount, dtype: float64